devices:
  names: [imu]
  imu:
    type: serial
    port: ~/dev/ttyIMU
    publish_rate: 40
    hardware_id: imu
    diagnostic_period: 1.0
    publisher:
      type: device_publishers/ImuPublisher
      topic_name: imu
      frame_id: imu_link
